//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.25 at 10:24:05 AM CST 
//


package com.jinbao.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dateFormat" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="varName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="varType" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="varVal" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "var")
public class Var {

    @XmlAttribute(name = "dateFormat", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dateFormat;
    @XmlAttribute(name = "varName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String varName;
    @XmlAttribute(name = "varType", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String varType;
    @XmlAttribute(name = "varVal", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String varVal;

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the varName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarName() {
        return varName;
    }

    /**
     * Sets the value of the varName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarName(String value) {
        this.varName = value;
    }

    /**
     * Gets the value of the varType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarType() {
        return varType;
    }

    /**
     * Sets the value of the varType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarType(String value) {
        this.varType = value;
    }

    /**
     * Gets the value of the varVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarVal() {
        return varVal;
    }

    /**
     * Sets the value of the varVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarVal(String value) {
        this.varVal = value;
    }

}
